services:
  php_cli:
    container_name: php_cli
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ../phel-lang:/usr/src
